apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-admin
  template:
    metadata:
      labels:
        app: web-admin
    spec:
      containers:
      - name: web-admin
        image: pmp-app/web-admin:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-admin
spec:
  selector:
    app: web-admin
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer



